version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
  build:
    commands:
      - echo Build started on `date`
      - python hello.py
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - hello.py
